# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19326f96e45877ed1d6b3bf49ae15abad66c11a200b365472d26be8d737d386bc2876297b7a4a3b6e52b35e3d39b7565981a7ebbe2476fc229058df6201a6629

test:
  secret_key_base: 6bdb21b18b1514ceda9791a1b2db3e31cfd05a07543bb39b166ad490d367605bad4fc1f03411f52785eb7cfb952811b460220e7c36696d0a59fd69d3a845018d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
